apiVersion: v1
kind: Service
metadata:
  name: aws-devops-demo-service
spec:
  type: LoadBalancer
  selector:
    app: aws-devops-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
